# Generated by Django 5.1.1 on 2024-11-28 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=100)),
                ('curso', models.TextField(max_length=100)),
                ('matricula', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.TextField(max_length=100)),
                ('contraseña', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.TextField(max_length=100)),
                ('nota', models.FloatField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Promedio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio', models.FloatField()),
                ('materia', models.TextField(max_length=100)),
                ('alumno_prom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.alumno')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='apoderado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.usuarios', unique=True),
        ),
    ]
