# Generated by Django 5.1.1 on 2024-11-28 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='apoderado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academico.usuarios', unique=True),
        ),
    ]
