# Generated by Django 5.1.1 on 2024-11-29 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_alter_alumno_apoderado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='apoderado',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='academico.usuarios'),
        ),
    ]
