# Generated by Django 5.1.1 on 2024-11-14 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_initial'),
    ]

    operations = [
    ]
